baseURL: https://www.jannestimm.com
# languageCode: en-us
title: Jannes
author: Jannes Timmm
description: personal website of Jannes Timm
keywords:
  - Jannes Timm

defaultContentLanguage: en
languages:
  en:
    languageName: English
    languageCode: en-us
    weight: 0
  zh:
    languageName: 简体中文
    languageCode: zh
    weight: 1

build:
  writeStats: true

module:
  hugoVersion:
    extended: false
    min: "0.75.0"

# don't build the "tags" and "categories" pages
disableKinds: ["taxonomy", "taxonomyTerm"]

# enable syntax highlighting
pygmentsCodefences: true
pygmentsStyle: pygments
