main:                                      
  - identifier: Home                      
    name: home                            
    url: /
    weight: 1                              
  - identifier: About                      
    name: about                            
    url: /about                            
    weight: 2                              
  - identifier: Projects
    name: projects
    url: /projects
    weight: 3
  - identifier: Notes
    name: notes
    url: /notes
    weight: 4