main:                                      
  - identifier: about                      
    name: About                            
    url: /about                            
    weight: 1                              
  - identifier: projects
    name: Projects
    url: /projects
    weight: 2
  - identifier: notes
    name: Notes
    url: /notes
    weight: 3