main:                                      
  - identifier: Home                      
    name: 首页                            
    url: /
    weight: 1                              
  - identifier: About                      
    name: 关于我                            
    url: /about                            
    weight: 2                              
  - identifier: Projects
    name: 项目
    url: /projects
    weight: 3
  - identifier: Notes
    name: 帖子
    url: /notes
    weight: 4